---
name: Fedora compose trigger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

env:
  COMPOSE_URL_F43: https://dl.fedoraproject.org/pub/fedora/linux/development/43
  COMPOSE_URL_RAWHIDE: https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide

jobs:
  check-compose:
    if: github.repository == 'virt-s1/rhel-edge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check if fedora 43 compose is new
        id: check_compose_id_43
        run: |
          curl -s "${COMPOSE_URL_F43}/COMPOSE_ID" --output COMPOSE_ID
          COMPOSE_ID=$(cat COMPOSE_ID)
          TESTED_COMPOSE=( $( cat compose/compose.f43 ) )
          if [[ " ${TESTED_COMPOSE[*]} " =~ "$COMPOSE_ID" ]]; then
              echo "need_pr=false" >> $GITHUB_OUTPUT
              exit 0
          fi

          gh pr list -R virt-s1/rhel-edge --state open --json title --jq '.[].title' > PR_LIST
          PR_LIST=$(cat PR_LIST)
          if [[ $PR_LIST == *"$COMPOSE_ID"* ]]; then
              echo "need_pr=false" >> $GITHUB_OUTPUT
              exit 0
          fi
          echo "need_pr=true" >> $GITHUB_OUTPUT
          echo "compose_id=$COMPOSE_ID" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if fedora rawhide compose is new
        id: check_compose_id_rawhide
        run: |
          curl -s "${COMPOSE_URL_RAWHIDE}/COMPOSE_ID" --output COMPOSE_ID
          COMPOSE_ID=$(cat COMPOSE_ID)
          TESTED_COMPOSE=( $( cat compose/compose.rawhide ) )
          if [[ " ${TESTED_COMPOSE[*]} " =~ "$COMPOSE_ID" ]]; then
              echo "need_pr=false" >> $GITHUB_OUTPUT
              exit 0
          fi

          gh pr list -R virt-s1/rhel-edge --state open --json title --jq '.[].title' > PR_LIST
          PR_LIST=$(cat PR_LIST)
          if [[ $PR_LIST == *"$COMPOSE_ID"* ]]; then
              echo "need_pr=false" >> $GITHUB_OUTPUT
              exit 0
          fi
          echo "need_pr=true" >> $GITHUB_OUTPUT
          echo "compose_id=$COMPOSE_ID" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      compose_id_rawhide: ${{ steps.check_compose_id_rawhide.outputs.compose_id }}
      need_pr_rawhide: ${{ steps.check_compose_id_rawhide.outputs.need_pr }}
      compose_id_43: ${{ steps.check_compose_id_43.outputs.compose_id }}
      need_pr_43: ${{ steps.check_compose_id_43.outputs.need_pr }}

  fedora-rawhide:
    needs: check-compose
    if: ${{ needs.check-compose.outputs.need_pr_rawhide == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add new compose id in compose.rawhide
        run: |
          compose_id="${{ needs.check-compose.outputs.compose_id_rawhide }}"
          echo $compose_id >> compose/compose.rawhide
          cat compose/compose.rawhide

      - name: Create Pull Request for fedora rawhide
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          title: "${{ needs.check-compose.outputs.compose_id_rawhide }}"
          branch: cpr
          branch-suffix: random
          base: main
          body: "${{ needs.check-compose.outputs.compose_id_rawhide }}"
          commit-message: "Add compose ID ${{ needs.check-compose.outputs.compose_id_rawhide }} to compose file"
          labels: |
            automated-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add a comment to trigger test workflow
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT }}
          issue-number: ${{ steps.create-pr.outputs.pull-request-number }}
          body: /test-rawhide

  fedora-43:
    needs: check-compose
    if: ${{ needs.check-compose.outputs.need_pr_43 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add new compose id in compose.f43
        run: |
          compose_id="${{ needs.check-compose.outputs.compose_id_43 }}"
          echo $compose_id >> compose/compose.f43
          cat compose/compose.f43

      - name: Create Pull Request for fedora 43
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          title: "${{ needs.check-compose.outputs.compose_id_43 }}"
          branch: cpr
          branch-suffix: random
          base: main
          body: "${{ needs.check-compose.outputs.compose_id_43 }}"
          commit-message: "Add compose ID ${{ needs.check-compose.outputs.compose_id_43 }} to compose file"
          labels: |
            automated-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add a comment to trigger test workflow
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT }}
          issue-number: ${{ steps.create-pr.outputs.pull-request-number }}
          body: /test-f43
